config/routes.rb
Rails.application.routes.draw do
  if Rails.env.development?
    mount GraphiQL::Rails::Engine, at: "/graphiql", graphql_path: "/graphql#execute"
  end
  post "/graphql", to: "graphql#execute"
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  get 'polly/index', to: "polly#convert"
  get 'maps/index'
  resources :quotes
end
Rails.application.routes.draw do
  get 'maps/index'
  resources :quotes
  resources :interventions, :only => [:new, :create]
  resources :employees
  resources :polly
  devise_for :users
  root 'home#index'
  get 'home/backOffice'
  get 'home/quote'
  get 'home/commercial'
  get 'home/residential'
  get 'home/chart'
  get 'maps' => 'maps#index'
  post '/create_lead' => 'home#create_lead'
  get 'dropbox/auth' => 'dropbox#auth'
  get 'dropboxauth_callback/' => 'dropbox#auth_callback'
  get 'interventions/customer_buildings' => "interventions#customer_buildings"
  get 'interventions/building_batteries' => "interventions#building_batteries"
  get 'interventions/batterie_columns' => "interventions#batterie_columns"
  get 'interventions/column_elevators' => "interventions#column_elevators"
  # get 'interventions/elevator_select' => 'interventions#elevator_select'
  get 'interventions/company_employees' => 'interventions#company_employees'
  #get 'interventions/new' => 'interventions#new'
end

app/models/quote.rb
class Quote < ApplicationRecord
end

app/controllers/quotes_controller.rb
require 'rest-client'
require "json"

class QuotesController < ApplicationController
  before_action :set_quote, only: %i[ show edit update destroy ]

  # GET /quotes or /quotes.json
  def index
    @quotes = Quote.all
  end

  # GET /quotes/1 or /quotes/1.json
  def show
  end

  # GET /quotes/new
  def new
    @quote = Quote.new
  end

  # GET /quotes/1/edit
  def edit
  end

  # POST /quotes or /quotes.json
  def create
    @quote = Quote.new(quote_params)
    respond_to do |format|
      if @quote.save
        quote_form = {
          email: "rocket_elevator_client@test.com", 
          priority: 1, 
          status: 2,
          type: "Feature Request",
          subject: "From #{@quote.price}",
          description: "building type: #{@quote.building_type}, " + " number of appartment: #{@quote.number_of_apartments}, " + " number of floor: #{@quote.number_of_floors}, " + " number of elevator: #{@quote.number_of_elevators}, " + " message: #{@quote.business_hours}",
        }.to_json
        puts quote_form
        quote_ticket = RestClient::Request.execute(
          method: :post, 
          url: "https://rocketelevator-support.freshdesk.com/api/v2/tickets",
          user: ENV['FRESHDESK_KEY'],
          password: "x",
          headers: {
            content_type: "application/json"
          },
          payload: quote_form
        )
        puts quote_ticket

      # if @quote.save
        format.html { redirect_to quote_url(@quote), notice: "Quote was successfully created." }
        format.json { render :show, status: :created, location: @quote }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @quote.errors, status: :unprocessable_entity }
      # end
      end
    end
  end

  # PATCH/PUT /quotes/1 or /quotes/1.json
  def update
    respond_to do |format|
      if @quote.update(quote_params)
        format.html { redirect_to quote_url(@quote), notice: "Quote was successfully updated." }
        format.json { render :show, status: :ok, location: @quote }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @quote.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /quotes/1 or /quotes/1.json
  def destroy
    @quote.destroy

    respond_to do |format|
      format.html { redirect_to quotes_url, notice: "Quote was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_quote
      @quote = Quote.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def quote_params
      params.require(:quote).permit(:building_type, :price, :number_of_apartments, :number_of_companies, :number_of_corporations, :number_of_floors, :number_of_basements, :number_of_parking_spots, :number_of_elevators, :maximum_occupancy, :business_hours)
    end
end

app/helpers/quotes_helper.rb
module QuotesHelper
end

app/views/quotes/_form.html.erb
<%= form_with(model: quote, local: true) do |form| %>
  <% if quote.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(quote.errors.count, "error") %> prohibited this quote from being saved:</h2>

      <ul>
      <% quote.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :building_type %>
    <%= form.select(:building_type, ['Residential', 'Commercial', 'Corporate', 'Hybrid']) %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.select(:price, ['Standard', 'Premium', 'Excelium']) %>
  </div>
    <%#= form.radio_button :contactmethod, 'email', :checked => true %> 
    <%#= label :contactmethod_email, 'Email' %>
    <%#= form.radio_button :contactmethod, 'sms' %>
    <%#= label :contactmethod_sms, 'SMS' %>

  <div class="field">
    <%= form.label :number_of_apartments %>
    <%= form.number_field :number_of_apartments %>
  </div>

  <div class="field">
    <%= form.label :number_of_companies %>
    <%= form.number_field :number_of_companies %>
  </div>

  <div class="field">
    <%= form.label :number_of_corporations %>
    <%= form.number_field :number_of_corporations %>
  </div>

  <div class="field">
    <%= form.label :number_of_floors %>
    <%= form.number_field :number_of_floors %>
  </div>

  <div class="field">
    <%= form.label :number_of_basements %>
    <%= form.number_field :number_of_basements %>
  </div>

  <div class="field">
    <%= form.label :number_of_parking_spots %>
    <%= form.number_field :number_of_parking_spots %>
  </div>

  <div class="field">
    <%= form.label :number_of_elevators %>
    <%= form.number_field :number_of_elevators %>
  </div>

  <div class="field">
    <%= form.label :maximum_occupancy %>
    <%= form.number_field :maximum_occupancy %>
  </div>

  <div class="field">
    <%= form.label :business_hours %>
    <%= form.number_field :business_hours %>
  </div>

  <div class="actions">
    <br>
    <%= form.submit class:"btn btn-secondary" %>
  </div>
<% end %>

app/views/quotes/edit.html.erb
<div class="container">
  <h1>Editing Quote</h1>
  
  <%= render 'form', quote: @quote %>
  
  <%= link_to 'Show', @quote %>
  <%#= link_to 'Back', quotes_path %>
</div>
<br>

app/views/quotes/index.html.erb
<br>
<br>
<br>
<p id="notice"><%= notice %></p>
<div class = "container">
  <h1>Quotes</h1>
</div>

<table class = "container table table-hover table-bordered table-striped">
  <thead class ="thead-dark">
    <tr>
      <th>Building type</th>
      <th>Price</th>
      <th>Number of apartments</th>
      <th>Number of companies</th>
      <th>Number of corporations</th>
      <th>Number of floors</th>
      <th>Number of basements</th>
      <th>Number of parking spots</th>
      <th>Number of elevators</th>
      <th>Maximum occupancy</th>
      <th>Business hours</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @quotes.each do |quote| %>
      <tr>
        <td><%= quote.building_type %></td>
        <td><%= quote.price %></td>
        <td><%= quote.number_of_apartments %></td>
        <td><%= quote.number_of_companies %></td>
        <td><%= quote.number_of_corporations %></td>
        <td><%= quote.number_of_floors %></td>
        <td><%= quote.number_of_basements %></td>
        <td><%= quote.number_of_parking_spots %></td>
        <td><%= quote.number_of_elevators %></td>
        <td><%= quote.maximum_occupancy %></td>
        <td><%= quote.business_hours %></td>
        <td><%= link_to 'Show', quote %></td>
        <td><%= link_to 'Edit', edit_quote_path(quote) %></td>
        <td><%= link_to 'Destroy', quote, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<div class = "container">
  <%= link_to 'New Quote', new_quote_path, class:"btn btn-secondary" %>
</div>
<br>

app/views/quotes/new.html.erb
<div class="container">
  <h1>New Quote</h1>
  
  <%= render 'form', quote: @quote %>
  
  <%#= link_to 'Back', quotes_path %>
</div>

app/views/quotes/quote.html.erb
<section id="quote">
	<div class="container">
		<h1 id="form-head">Quote Form</h1>
		<form id="quote-form">
			<div class="row">
				<div class="col">
					<label for="building-type">Building Type</label>
				</div>
				<div class="col">
					<select id="building-type" style="padding: 0px 4px">
						<option id="select" value="select"><--Selection--></option>
						<option id="residential" value="residential">Residential</option>
						<option id="commercial" value="commercial">Commercial</option>
						<option id="corporate" value="corporate">Corporate</option>
						<option id="hybrid" value="hybrid">Hybrid</option>
					</select>
				</div>
			</div>
			<br>
			<div id="number-of-apartments" class="field row quote-input residential">
				<div class="col">
					<label>N. of Apartments</label>
				</div>
				<div class="col">
					<input type="text" required placeholder="#Apartments" /> </div>
			</div>
			<div id="number-of-companies" class="field row quote-input commercial hybrid">
				<div class="col">
					<label>N. of Companies</label>
				</div>
				<div class="col">
					<input type="text" required placeholder="#Companies" /> </div>
			</div>
			<div id="number-of-corporations" class="field row quote-input corporate">
				<div class="col">
					<label>N. of Corporations</label>
				</div>
				<div class="col">
					<input type="text" required placeholder="#Corporations" /> </div>
			</div>
			<div id="number-of-floors" class="field row quote-input residential commercial corporate hybrid">
				<div class="col">
					<label>N. of Floors</label>
				</div>
				<div class="col">
					<input type="text" required placeholder="#Floors" /> </div>
			</div>
			<div id="number-of-basements" class="field row quote-input residential commercial corporate hybrid">
				<div class="col">
					<label>N. of Basements</label>
				</div>
				<div class="col">
					<input type="text" required placeholder="#Basements" /> </div>
			</div>
			<div id="number-of-parking-spots" class="field row quote-input commercial corporate hybrid">
				<div class="col">
					<label>N. of Parking Spots</label>
				</div>
				<div class="col">
					<input type="text" required placeholder="#Parking Spots" /> </div>
			</div>
			<div id="number-of-elevators" class="field row quote-input commercial">
				<div class="col">
					<label>N. of Elevators</label>
				</div>
				<div class="col">
					<input type="text" required placeholder="#Elevators" /> </div>
			</div>
			<div id="maximum-occupancy" class="field row quote-input corporate hybrid">
				<div class="col">
					<label>N. of Occupants Per Floor</label>
				</div>
				<div class="col">
					<input type="text" required placeholder="#Occupants/Floors" /> </div>
			</div>
			<div id="business-hours" class="field row quote-input hybrid">
				<div class="col">
					<label>N. of Hours of Activity of The Building</label>
				</div>
				<div class="col">
					<input type="text" required placeholder="#Hours (Max 24)" /> </div>
			</div>
			<div id="answers">
				<h2>Select Plan</h2>
				<div class="row">
					<div class="col">
						<label>
							<input id="standard" type="radio" name="price" value="standard" checked>Standard</label>
					</div>
					<div class="col">
						<label>
							<input id="premium" type="radio" name="price" value="premium">Premium</label>
					</div>
					<div class="col">
						<label>
							<input id="excelium" type="radio" name="price" value="excelium">Excelium</label>
					</div>
				</div>
				<div id="elevator-amount" class="row">
					<div class="col">
						<label>Total Elevators:</label>
					</div>
					<div class="col">
						<input type="text" readonly value="0" /> </div>
				</div>
				<div id="elevator-unit-price" class="row">
					<div class="col">
						<label>Elevator Price:</label>
					</div>
					<div class="col">
						<input type="text" readonly value="$0" /> </div>
				</div>
				<div id="elevator-total-price" class="row">
					<div class="col">
						<label>Elevator Total Price:</label>
					</div>
					<div class="col">
						<input type="text" readonly value="$0" /> </div>
				</div>
				<div id="installation-fees" class="row">
					<div class="col">
						<label>Installation Fees:</label>
					</div>
					<div class="col">
						<input type="text" readonly value="$0" /> </div>
				</div>
				<div id="final-price" class="row">
					<div class="col">
						<label>Total Price:</label>
					</div>
					<div class="col">
						<input type="text" readonly value="$0" /> </div>
				</div>
			</div>
		</form>
	</div>
</section>
<section class="parallax parallax-1" style="background-image: url('r_assets/M.jpg');">
	<div class="overlay dark-3"></div>
	<div class="container">
		<div class="text-center">
			<h2 class="fs-40 fw-300">Reaching for the Stars since 1976</h2> <a class="btn btn-default btn-lg" href="#">GET A QUOTE</a> &nbsp; OR &nbsp;
			<%= link_to 'CONTACT US',root_path,class:'btn btn-primary btn-lg'%>
		</div>
	</div>
</section>

app/views/quotes/show.html.erb
<div class="container jumbotron">
  <br>
  <br>
  <p id="notice"><%= notice %></p>
  
  <p>
    <strong>Building type:</strong>
    <%= @quote.building_type %>
  </p>
  
  <p>
    <strong>Price:</strong>
    <%= @quote.price %>
  </p>
  
  <p>
    <strong>Number of apartments:</strong>
    <%= @quote.number_of_apartments %>
  </p>
  
  <p>
    <strong>Number of companies:</strong>
    <%= @quote.number_of_companies %>
  </p>
  
  <p>
    <strong>Number of corporations:</strong>
    <%= @quote.number_of_corporations %>
  </p>
  
  <p>
    <strong>Number of floors:</strong>
    <%= @quote.number_of_floors %>
  </p>
  
  <p>
    <strong>Number of basements:</strong>
    <%= @quote.number_of_basements %>
  </p>
  
  <p>
    <strong>Number of parking spots:</strong>
    <%= @quote.number_of_parking_spots %>
  </p>
  
  <p>
    <strong>Number of elevators:</strong>
    <%= @quote.number_of_elevators %>
  </p>
  
  <p>
    <strong>Maximum occupancy:</strong>
    <%= @quote.maximum_occupancy %>
  </p>
  
  <p>
    <strong>Business hours:</strong>
    <%= @quote.business_hours %>
  </p>
  
  <%= link_to 'Edit', edit_quote_path(@quote) %> 
  <br>
  <br>
  <%= link_to 'Back', new_quote_path %>
</div>