config/routes.rb
Rails.application.routes.draw do
  if Rails.env.development?
    mount GraphiQL::Rails::Engine, at: "/graphiql", graphql_path: "/graphql#execute"
  end
  post "/graphql", to: "graphql#execute"
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  get 'polly/index', to: "polly#convert"
  get 'maps/index'
  resources :quotes
end
Rails.application.routes.draw do
  get 'maps/index'
  resources :quotes
  resources :interventions, :only => [:new, :create]
  resources :employees
  resources :polly
  devise_for :users
  root 'home#index'
  get 'home/backOffice'
  get 'home/quote'
  get 'home/commercial'
  get 'home/residential'
  get 'home/chart'
  get 'maps' => 'maps#index'
  post '/create_lead' => 'home#create_lead'
  get 'dropbox/auth' => 'dropbox#auth'
  get 'dropboxauth_callback/' => 'dropbox#auth_callback'
  get 'interventions/customer_buildings' => "interventions#customer_buildings"
  get 'interventions/building_batteries' => "interventions#building_batteries"
  get 'interventions/batterie_columns' => "interventions#batterie_columns"
  get 'interventions/column_elevators' => "interventions#column_elevators"
  # get 'interventions/elevator_select' => 'interventions#elevator_select'
  get 'interventions/company_employees' => 'interventions#company_employees'
  #get 'interventions/new' => 'interventions#new'
end

app/controllers/home_controller.rb
require 'sendgrid-ruby'
include SendGrid
require 'dropbox_api'
require 'rest-client'
require "json"

class HomeController < ApplicationController

  def index
    # if current_user
    #   if current_user.admin == 1
    #     redirect_to rails_admin_path
    #   end
    # end
  end
  
  def chart 
    if current_user.admin != 1
        redirect_to root_path
    end
  end


  def create_lead
    pp params[:file]
    @lead = Lead.new(params.permit(:name, :company_name, :email, :phone, :project_name , :description , :department , :message , :file , :date))
    @params_email = params.permit(:email, :name, :project_name)

    puts 'START OF DROPBOX PROCESS'
    if @lead.file.attached?
      puts @lead.file.attached?
      dbx = DropboxApi::Client.new(ENV['DROPBOX_OAUTH_BEARER'])
      puts 'AUTHENTICATED'
      filename_path = ActiveStorage::Blob.service.send(:path_for, @lead.file.key)
      puts "YOOOOOOOOOOOO"
      pp filename_path
      new_filename = "#{@lead.company_name.parameterize}/#{@lead.file.filename.to_s}"
      puts "HEEEEEEEEEEEEEEEEEEEY"
      puts new_filename
      file = dbx.upload(filename_path, 'https://www.dropbox.com/home/Apps/RocketElevatorFileHolder') # Accepts a String or File
      puts 'FILES IN DROPBOX APP'
    end

    if @lead.save
      send_mail(@params_email)
      redirect_to root_path, notice: "Contact successfully submitted."
      data = {
        email: "#{@lead.email}", 
        priority: 1, 
        status: 2,
        type: "Question",
        subject: "#{@lead.name} from #{@lead.company_name}",
        description: "The contact #{@lead.name} from company #{@lead.company_name} can be reached at email #{@lead.email} and at phone number #{@lead.phone}. 
        #{@lead.department} has a project named #{@lead.project_name} which would require contribution from Rocket Elevators. 
        #{@lead.description}",
      }.to_json
      request  = RestClient::Request.execute(
        method: :post, 
        url: 'https://rocketelevator-support.freshdesk.com/api/v2/tickets',
        user: ENV['FRESHDESK_KEY'],
        password: "x",
        headers: {
          content_type: "application/json"
        },
        payload: data
      )
    else
      render plain: @lead.errors.full_messages
    end
    
    if @lead.file.attached?
      dbx = DropboxApi::Client.new(ENV['DROPBOX_OAUTH_BEARER'])
      filename_path = ActiveStorage::Blob.service.send(:path_for, @lead.file.key)
      new_filename = "#{@lead.company_name.parameterize}/#{@lead.file.filename.to_s}"
      file = dbx.upload(new_filename, 'https://www.dropbox.com/home/Apps/RocketElevatorFileHolder') # Accepts a String or File
    end
  end

  def send_mail(params_email)
    email = params_email['email']
    name = params_email['name']
    project_name = params_email['project_name']
    from = SendGrid::Email.new(email: 'sevada.rostomian@gmail.com')
    to = SendGrid::Email.new(email: email)
    subject = 'Response to contact.'
    content = Content.new(type: 'text/html', value: 'Greetings ' + name +
      ',<br>
      <br>
      We thank you for contacting Rocket Elevators to discuss the opportunity to contribute to your project ' + project_name + '.
      <br>
      <br>
      A representative from our team will be in touch with you very soon. We look forward to demonstrating the value of our solutions and helping you choose the appropriate product given your requirements.
      <br>
      <br>
      We’ll Talk soon
      <br>
      The Rocket Team
      <br>
      <br>
      <img src="https://i.imgur.com/M5G13C8.png" width="200">')
    mail = SendGrid::Mail.new(from, subject, to, content)


    sg = SendGrid::API.new(api_key: ENV['SENDGRID_API_KEY'])
    response = sg.client.mail._('send').post(request_body: mail.to_json)
    puts response.status_code
    puts response.body
    puts response.headers
  end
end


app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_footer.html.erb
<footer id="footer">
    <div class="container">
        <div class="row">
            <!-- col #1 -->
            <div class="col-md-8">
                <h3 class="letter-spacing-1">WHY US?</h3>
                <!-- Small Description -->
                <p>
                    Why is the great question we all must ask when our minds finally develop the ability to comprehend its own existence. WHY US? We have the conviction that we create the most innovative and reliable products on the market. Contact us today for any questions you might have.
                </p>
                <h2>(418) 555-1234</h2>
            </div>
            <!-- /col #1 -->
            <!-- col #2 -->
            <div class="col-md-4">
                <h3 class="letter-spacing-1">KEEP IN TOUCH</h3>
                <!-- Newsletter Form -->
                <p>Subscribe to Our Newsletter to get Important News & Offers</p>
                <form class="validate" action="php/newsletter.php" method="post" data-success="Subscribed! Thank you!" data-toastr-position="bottom-right">
                    <div class="input-group">
                        <input type="email" id="email" name="email" class="form-control required" placeholder="Enter your Email">
                        <span class="input-group-btn">
                            <button class="btn btn-success" type="submit">Subscribe</button>
                        </span>
                    </div>
                </form>
                <!-- /Newsletter Form -->
            </div>
            <!-- /col #2 -->
        </div>
    </div>
    <div class="copyright">
        <div class="container">
            <ul class="float-right m-0 list-inline mobile-block">
                <li><a href="#top">Terms &amp; Conditions</a></li>
                <li>&bull;</li>
                <li><a href="#top">Privacy</a></li>
            </ul>
            &copy; All Rights Reserved, Rocket Elevators INC.
        </div>
    </div>
</footer>



app/views/home/_header.html.erb
<div id="header" class="navbar-toggleable-md header-md clearfix">
    <!-- TOP NAV -->
    <header id="topNav">
        <div class="container">
            <!-- Mobile Menu Button -->
            <button class="btn btn-mobile" data-toggle="collapse" data-target=".nav-main-collapse">
                <i class="fa fa-bars"></i>
            </button>
            <!-- Logo -->
            <a class="logo float-left scrollTo" href="#top">
                <%= image_tag "R3.png"%>
            </a>
            <div class="navbar-collapse collapse float-right nav-main-collapse submenu-dark">
                <nav class="nav-main">
                    <ul id="topMain" class="nav nav-pills nav-main nav-onepage">
                        <li class="active"><!-- HOME -->
                            <%= link_to 'HOME', root_path %>
                        </li>
                        <li><!-- SERVICES -->
                            <%=link_to 'SERVICES', root_path(anchor: 'services')%>
                        </li>
                        <li><!-- PORTFOLIO -->
                            <%=link_to 'PORTFOLIO', root_path(anchor: 'portfolio')%>
                        </li>
                        <li><!-- NEWS -->
                            <%=link_to 'NEWS', root_path(anchor: 'news')%>
                        </li>
                        <li><!-- CLIENTS -->
                            <%=link_to 'CLIENTS', root_path(anchor: 'clients')%>
                        </li>
                        <li><!-- CONTACT -->
                            <%=link_to 'CONTACT', root_path(anchor: 'contact')%>
                        </li>
                        <li>
                            <%=link_to 'INTERVENTIONS', new_intervention_path,class:"nav-link" %>
                        </li>


                        <%#logic to show and hide when a user has signed in%>
                        <%# <li class="nav-item">
                            <%= link_to "EMPLOYEE LIST",employees_path, class:"nav-link"
                        </li> %>


                        <% if user_signed_in?%>
                            <%# <li class="nav-item">
                            <%= link_to"Add User",new_user_registration_path ,class:"nav-link"%> 
                            <li class="nav-item">
                                <%= link_to"Admin",rails_admin_path,class:"nav-link"%>
                            </li>

                            <li class ="nav-item">
                                <%= link_to"Chart",home_chart_path,class:"nav-link"%>
                            </li>

                            <li class="nav-item">
                                <%= button_to "SIGN OUT",destroy_user_session_path, method: :delete, class:"btn-link"%>
                            </li>
                        <%else%>
                            <li class="nav-item">
                                <%= link_to"SIGN UP",new_user_registration_path ,class:"nav-link"%>
                            </li>
                            <li class="nav-item text-light bg-primary">
                                <%= link_to"SIGN IN",new_user_session_path ,class:"nav-link text-light"%>
                            </li>
                        <%end%>
                    </ul>
                </nav>
            </div>
        </div>
    </header>
    <!-- /Top Nav -->
</div>

app/views/home/chart.erb
<div class = "container">

    <br>
    <br>
    <br>
    <br>
    <br>
    <%##############################################################################################################################################################################%>
    <%
    def get_customer_elevators(customer_id)
    nb_elevators = 0
        customer = Customer.find(customer_id)
            customer.buildings.each do |building|
                building.batteries.each do |battery|
                    battery.columns.each do |column|
                        column.elevators.each do |elevator|
                            nb_elevators += 1
                        end
                    end
                end
            end
        nb_elevators
    end
    dictionaryQ3 = {}
    Customer.all.each do |c|
        dictionaryQ3[c.company_name] = get_customer_elevators(c.id)
    end
    ################################################################################################################################################################################
    def contact_per_month()
        dQ1 = {}
        dQ1["Jan"] = 0
        dQ1["Feb"] = 0
        dQ1["Mar"] = 0
        dQ1["Api"] = 0
        dQ1["May"] = 0
        dQ1["Jun"] = 0
        dQ1["Jul"] = 0
        dQ1["Auq"] = 0
        dQ1["Sep"] = 0
        dQ1["Oct"] = 0
        dQ1["Nov"] = 0
        dQ1["Dec"] = 0


    Lead.all.each do |l|
        Lead.find(l.id)
                if l.date.month == 1 
                    dQ1["Jan"] += 1
                    
                elsif l.date.month == 2
                    dQ1["Feb"] += 1
                    
                elsif l.date.month == 3
                    dQ1["Mar"] += 1
                    
                elsif l.date.month == 4
                    dQ1["Api"] += 1
                    
                elsif l.date.month == 5
                    dQ1["May"] += 1
                    
                elsif l.date.month == 6
                    dQ1["Jun"] += 1
                    
                elsif l.date.month == 7
                    dQ1["Jul"] += 1
                    
                elsif l.date.month == 8
                    dQ1["Auq"] += 1
                    
                elsif l.date.month == 9
                    dQ1["Sep"] += 1
                    
                elsif l.date.month == 10
                    dQ1["Oct"] += 1
                    
                elsif l.date.month == 11
                    dQ1["Nov"] += 1
                    
                else l.date.month == 12
                    dQ1["Dec"] += 1
                end   
            end
        dQ1
    end
    #######################################################################################################################################################################
    def no_of_quotes_per_month()
        dQ2 = {}
        dQ2["Jan"] = 0
        dQ2["Feb"] = 0
        dQ2["Mar"] = 0
        dQ2["Api"] = 0
        dQ2["May"] = 0
        dQ2["Jun"] = 0
        dQ2["Jul"] = 0
        dQ2["Auq"] = 0
        dQ2["Sep"] = 0
        dQ2["Oct"] = 0
        dQ2["Nov"] = 0
        dQ2["Dec"] = 0


        Quote.all.each do |q|
        Quote.find(q.id)
                if q.date.month == 1 
                    dQ2["Jan"] += 1
                    
                elsif q.date.month == 2
                    dQ2["Feb"] += 1
                    
                elsif q.date.month == 3
                    dQ2["Mar"] += 1
                    
                elsif q.date.month == 4
                    dQ2["Api"] += 1
                    
                elsif q.date.month == 5
                    dQ2["May"] += 1
                    
                elsif q.date.month == 6
                    dQ2["Jun"] += 1
                    
                elsif q.date.month == 7
                    dQ2["Jul"] += 1
                    
                elsif q.date.month == 8
                    dQ2["Auq"] += 1
                    
                elsif q.date.month == 9
                    dQ2["Sep"] += 1
                    
                elsif q.date.month == 10
                    dQ2["Oct"] += 1
                    
                elsif q.date.month == 11
                    dQ2["Nov"] += 1
                    
                else q.date.month == 12
                    dQ2["Dec"] += 1
                end   
            end
        dQ2
    end%>
    <%#############################################################################################################################################################################%>
    <div>
        <div>
            <h3 class = "text-center">A visual represntation of Contact request per Month, Quote solications per Month and Elevators per Customer<h3>
        </div>

        <div>
            
            <br>
            <hr>
            <h4 class = "text-center">Contact Requests Made Per Month<h4>
            <hr>
            <%=bar_chart contact_per_month()%>
        </div>

        <div>
            <br>
            <br>
            <hr>
            <h4 class = "text-center">Quote Solicitions Per Month<h4>
            <hr>
            <%=column_chart no_of_quotes_per_month()%>
            <hr>
        </div>

        <div>
            <br>
            <br>
            <hr>
            <h4 class = "text-center">Elvators per Customer<h4>
            <hr>
            <%=bar_chart dictionaryQ3%>
        </div>
    </div>
    <br>
    <br>
    <br>
</div>

app/views/home/commercial.html.erb
<!-- REVOLUTION SLIDER -->
<div class="jumbotron" style="margin: 0 0;padding: 7rem 4rem 2rem;">
  <h2 class="display-4">Reaching for the Stars since 1976</h2>
  <hr class="my-4">
</div>
<!-- /REVOLUTION SLIDER -->
<!-- Parallax -->
<section class="parallax parallax-1" style="background-image: url('r_assets/M.jpg');">
	<div class="overlay dark-3">
		<!-- dark overlay [1 to 9 opacity] -->
	</div>
	<div class="container">
		<div class="text-center">
			<h2 class="fs-40 fw-300">Reaching for the Stars since 1976</h2>
			<%= link_to 'GET A QUOTE', new_quote_path, class:'btn btn-default btn-lg' %> &nbsp; OR &nbsp; <a class="btn btn-primary btn-lg" href="#contact">CONTACT US</a> </div>
	</div>
</section>
<!-- /Parallax -->
<!-- CONTACT -->
<section id="contact" style="padding: 50px 0px;">
	<div class="container">
		<header class="text-center mb-60">
			<h2>Contact Us</h2>
			<p class="lead font-lato">Any unwarranted contact will result in legal action.</p>
			<hr /> </header>
		<div class="row">
			<!-- FORM -->
			<div class="col-md-8 col-sm-8">
				<h3>Wanna let us in on the <strong><em>goods? </em></strong></h3>
				<!-- Alert Success -->
				<div id="alert_success" class="alert alert-success mb-30">
					<button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button> <strong>Thank You!</strong> Your message successfully sent! </div>
				<!-- /Alert Success -->
				<!-- Alert Failed -->
				<div id="alert_failed" class="alert alert-danger mb-30">
					<button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button> <strong>[SMTP] Error!</strong> Internal server error! </div>
				<!-- /Alert Failed -->
				<!-- Alert Mandatory -->
				<div id="alert_mandatory" class="alert alert-danger mb-30">
					<button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button> <strong>Sorry!</strong> You need to complete all mandatory (*) fields! </div>
				<!-- /Alert Mandatory -->
		<%= form_with(model: @lead, url: "/create_lead") do |form| %>
			<div class="row">
				<div class="field col-md-4">
					<%= form.label :name %>
					<%= form.text_field :name, class: "form-control pointer" %>
				</div>
				<div class="field col-md-4">
					<%= form.label :company_name %>
					<%= form.text_field :company_name, class: "form-control pointer" %>
				</div>
				<div class="field col-md-4">
					<%= form.label :email %>
					<%= form.text_field :email, class: "form-control pointer" %>
				</div>
				<div class="field col-md-4">
					<%= form.label :phone %>
					<%= form.text_field :phone, class: "form-control pointer" %>
				</div>
				<div class="field col-md-4">
					<%= form.label :project_name %>
					<%= form.text_field :project_name, class: "form-control pointer" %>
				</div>
				<div class="field col-md-4">
					<%= form.label :date %>
					<%= form.text_field :date, :readonly => true, value: Date.today, class: "form-control pointer" %>
				</div>
			</div>

			<div class="row">
				<div class="field col-md-8">
					<%= form.label :description %>
					<%= form.text_field :description, class: "form-control pointer" %>
				</div>
				<div class="field col-md-4">
					<%= form.label :department %>
					<%= form.select(:department, ["Support", "HR", "Juice", "Elevator Heads", "IT"], {}, { :style => "padding: 0px 4 px", class: "form-control pointer"})%>
				</div>
			</div>

			<div class="row">
				<div class="field col-md-12">
					<%= form.label :message %>
					<%= form.text_area :message, rows: 10, class: "form-control pointer"%>
				</div>
			</div>

			<div class="row">
				<div class="field col-md-12">
					<%= form.label :file %>
					<%= form.file_field :file %>
				</div>
			</div>


			<div class="actions">
				<%= form.submit %>
			</div>
		<% end %>
		
			</div>
			<!-- /FORM -->
			<!-- INFO -->
			<div class="col-md-4 col-sm-4">
				<h2>Visit Us</h2>
				<div id="map2" class="h-400"></div>
				<hr />
				<p> <span class="block"><strong>Address:</strong> 4468 Wellington St Suite 204, Verdun, Quebec H4G 1W5</span> <span class="block"><strong>Phone:</strong> <a href="tel:(418) 555-1234">(418) 555-1234</a></span> <span class="block"><strong>Email:</strong> <a href="mailto:info@codeboxx.biz">info@codeboxx.biz</a></span> </p>
			</div>
			<!-- /INFO -->
		</div>
	</div>
</section>
<!-- /CONTACT -->

app/views/home/quote.html.erb
<section id="quote">
	<div class="container">
		<h1 id="form-head">Quote Form</h1>
		<form id="quote-form">
			<div class="row">
				<div class="col">
					<label for="building-type">Building Type</label>
				</div>
				<div class="col">
					<select id="building-type" style="padding: 0px 4px">
						<option id="select" value="select">
							<--Selection-->
						</option>
						<option id="residential" value="residential">Residential</option>
						<option id="commercial" value="commercial">Commercial</option>
						<option id="corporate" value="corporate">Corporate</option>
						<option id="hybrid" value="hybrid">Hybrid</option>
					</select>
				</div>
			</div>
			<br>
			<div id="number-of-apartments" class="row quote-input residential">
				<div class="col">
					<label>N. of Apartments</label>
				</div>
				<div class="col">
					<input type="text" required placeholder="#Apartments" /> </div>
			</div>
			<div id="number-of-companies" class="row quote-input commercial hybrid">
				<div class="col">
					<label>N. of Companies</label>
				</div>
				<div class="col">
					<input type="text" required placeholder="#Companies" /> </div>
			</div>
			<div id="number-of-corporations" class="row quote-input corporate">
				<div class="col">
					<label>N. of Corporations</label>
				</div>
				<div class="col">
					<input type="text" required placeholder="#Corporations" /> </div>
			</div>
			<div id="number-of-floors" class="row quote-input residential commercial corporate hybrid">
				<div class="col">
					<label>N. of Floors</label>
				</div>
				<div class="col">
					<input type="text" required placeholder="#Floors" /> </div>
			</div>
			<div id="number-of-basements" class="row quote-input residential commercial corporate hybrid">
				<div class="col">
					<label>N. of Basements</label>
				</div>
				<div class="col">
					<input type="text" required placeholder="#Basements" /> </div>
			</div>
			<div id="number-of-parking-spots" class="row quote-input commercial corporate hybrid">
				<div class="col">
					<label>N. of Parking Spots</label>
				</div>
				<div class="col">
					<input type="text" required placeholder="#Parking Spots" /> </div>
			</div>
			<div id="number-of-elevators" class="row quote-input commercial">
				<div class="col">
					<label>N. of Elevators</label>
				</div>
				<div class="col">
					<input type="text" required placeholder="#Elevators" /> </div>
			</div>
			<div id="maximum-occupancy" class="row quote-input corporate hybrid">
				<div class="col">
					<label>N. of Occupants Per Floor</label>
				</div>
				<div class="col">
					<input type="text" required placeholder="#Occupants/Floors" /> </div>
			</div>
			<div id="business-hours" class="row quote-input hybrid">
				<div class="col">
					<label>N. of Hours of Activity of The Building</label>
				</div>
				<div class="col">
					<input type="text" required placeholder="#Hours (Max 24)" /> </div>
			</div>
			<div id="answers">
				<h2>Select Plan</h2>
				<div class="row">
					<div class="col">
						<label>
							<input id="standard" type="radio" name="price" value="standard" checked>Standard</label>
					</div>
					<div class="col">
						<label>
							<input id="premium" type="radio" name="price" value="premium">Premium</label>
					</div>
					<div class="col">
						<label>
							<input id="excelium" type="radio" name="price" value="excelium">Excelium</label>
					</div>
				</div>
				<div id="elevator-amount" class="row">
					<div class="col">
						<label>Total Elevators:</label>
					</div>
					<div class="col">
						<input type="text" readonly value="0" /> </div>
				</div>
				<div id="elevator-unit-price" class="row">
					<div class="col">
						<label>Elevator Price:</label>
					</div>
					<div class="col">
						<input type="text" readonly value="$0" /> </div>
				</div>
				<div id="elevator-total-price" class="row">
					<div class="col">
						<label>Elevator Total Price:</label>
					</div>
					<div class="col">
						<input type="text" readonly value="$0" /> </div>
				</div>
				<div id="installation-fees" class="row">
					<div class="col">
						<label>Installation Fees:</label>
					</div>
					<div class="col">
						<input type="text" readonly value="$0" /> </div>
				</div>
				<div id="final-price" class="row">
					<div class="col">
						<label>Total Price:</label>
					</div>
					<div class="col">
						<input type="text" readonly value="$0" /> </div>
				</div>
			</div>
		</form>
	</div>
</section>
<section class="parallax parallax-1" style="background-image: url('r_assets/M.jpg');">
	<div class="overlay dark-3"></div>
	<div class="container">
		<div class="text-center">
			<h2 class="fs-40 fw-300">Reaching for the Stars since 1976</h2> <a class="btn btn-default btn-lg" href="#">GET A QUOTE</a> &nbsp; OR &nbsp;
			<%= link_to 'CONTACT US',root_path,class:'btn btn-primary btn-lg'%>
		</div>
	</div>
</section>

app/views/home/residential.html.erb
<!-- REVOLUTION SLIDER -->
<div class="jumbotron" style="margin: 0 0;padding: 7rem 4rem 2rem;">
  <h2 class="display-4">Reaching for the Stars since 1976</h2>
  <hr class="my-4">
</div>
<!-- /REVOLUTION SLIDER -->
<!-- Parallax -->
<section class="parallax parallax-1" style="background-image: url('r_assets/M.jpg');">
	<div class="overlay dark-3">
		<!-- dark overlay [1 to 9 opacity] -->
	</div>
	<div class="container">
		<div class="text-center">
			<h2 class="fs-40 fw-300">Reaching for the Stars since 1976</h2>
			<%= link_to 'GET A QUOTE', new_quote_path, class:'btn btn-default btn-lg' %> &nbsp; OR &nbsp; <a class="btn btn-primary btn-lg" href="#contact">CONTACT US</a> </div>
	</div>
</section>
<!-- /Parallax -->
<!-- CONTACT -->
<section id="contact" style="padding: 50px 0px;">
	<div class="container">
		<header class="text-center mb-60">
			<h2>Contact Us</h2>
			<p class="lead font-lato">Any unwarranted contact will result in legal action.</p>
			<hr /> </header>
		<div class="row">
			<!-- FORM -->
			<div class="col-md-8 col-sm-8">
				<h3>Wanna let us in on the <strong><em>goods? </em></strong></h3>
				<!-- Alert Success -->
				<div id="alert_success" class="alert alert-success mb-30">
					<button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button> <strong>Thank You!</strong> Your message successfully sent! </div>
				<!-- /Alert Success -->
				<!-- Alert Failed -->
				<div id="alert_failed" class="alert alert-danger mb-30">
					<button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button> <strong>[SMTP] Error!</strong> Internal server error! </div>
				<!-- /Alert Failed -->
				<!-- Alert Mandatory -->
				<div id="alert_mandatory" class="alert alert-danger mb-30">
					<button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button> <strong>Sorry!</strong> You need to complete all mandatory (*) fields! </div>
				<!-- /Alert Mandatory -->
		<%= form_with(model: @lead, url: "/create_lead") do |form| %>
			<div class="row">
				<div class="field col-md-4">
					<%= form.label :name %>
					<%= form.text_field :name, class: "form-control pointer" %>
				</div>
				<div class="field col-md-4">
					<%= form.label :company_name %>
					<%= form.text_field :company_name, class: "form-control pointer" %>
				</div>
				<div class="field col-md-4">
					<%= form.label :email %>
					<%= form.text_field :email, class: "form-control pointer" %>
				</div>
				<div class="field col-md-4">
					<%= form.label :phone %>
					<%= form.text_field :phone, class: "form-control pointer" %>
				</div>
				<div class="field col-md-4">
					<%= form.label :project_name %>
					<%= form.text_field :project_name, class: "form-control pointer" %>
				</div>
				<div class="field col-md-4">
					<%= form.label :date %>
					<%= form.text_field :date, :readonly => true, value: Date.today, class: "form-control pointer" %>
				</div>
			</div>

			<div class="row">
				<div class="field col-md-8">
					<%= form.label :description %>
					<%= form.text_field :description, class: "form-control pointer" %>
				</div>
				<div class="field col-md-4">
					<%= form.label :department %>
					<%= form.select(:department, ["Support", "HR", "Juice", "Elevator Heads", "IT"], {}, { :style => "padding: 0px 4 px", class: "form-control pointer"})%>
				</div>
			</div>

			<div class="row">
				<div class="field col-md-12">
					<%= form.label :message %>
					<%= form.text_area :message, rows: 10, class: "form-control pointer"%>
				</div>
			</div>

			<div class="row">
				<div class="field col-md-12">
					<%= form.label :file %>
					<%= form.file_field :file %>
				</div>
			</div>


			<div class="actions">
				<%= form.submit %>
			</div>
		<% end %>
		
			</div>
			<!-- /FORM -->
			<!-- INFO -->
			<div class="col-md-4 col-sm-4">
				<h2>Visit Us</h2>
				<div id="map2" class="h-400"></div>
				<hr />
				<p> <span class="block"><strong>Address:</strong> 4468 Wellington St Suite 204, Verdun, Quebec H4G 1W5</span> <span class="block"><strong>Phone:</strong> <a href="tel:(418) 555-1234">(418) 555-1234</a></span> <span class="block"><strong>Email:</strong> <a href="mailto:info@codeboxx.biz">info@codeboxx.biz</a></span> </p>
			</div>
			<!-- /INFO -->
		</div>
	</div>
</section>
<!-- /CONTACT -->

app/views/home/show.html.erb
<%= link_to 'View Image', '<ActiveStorage::Attached::One:0x00007f88ebf16398>' %>