config/routes.rb
Rails.application.routes.draw do
  if Rails.env.development?
    mount GraphiQL::Rails::Engine, at: "/graphiql", graphql_path: "/graphql#execute"
  end
  post "/graphql", to: "graphql#execute"
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  get 'polly/index', to: "polly#convert"
  get 'maps/index'
  resources :quotes
end
Rails.application.routes.draw do
  get 'maps/index'
  resources :quotes
  resources :interventions, :only => [:new, :create]
  resources :employees
  resources :polly
  devise_for :users
  root 'home#index'
  get 'home/backOffice'
  get 'home/quote'
  get 'home/commercial'
  get 'home/residential'
  get 'home/chart'
  get 'maps' => 'maps#index'
  post '/create_lead' => 'home#create_lead'
  get 'dropbox/auth' => 'dropbox#auth'
  get 'dropboxauth_callback/' => 'dropbox#auth_callback'
  get 'interventions/customer_buildings' => "interventions#customer_buildings"
  get 'interventions/building_batteries' => "interventions#building_batteries"
  get 'interventions/batterie_columns' => "interventions#batterie_columns"
  get 'interventions/column_elevators' => "interventions#column_elevators"
  # get 'interventions/elevator_select' => 'interventions#elevator_select'
  get 'interventions/company_employees' => 'interventions#company_employees'
  #get 'interventions/new' => 'interventions#new'
end

app/models/intervention.rb
class Intervention < ApplicationRecord
    # belongs_to :customer, class_name: "Customer", foreign_key: "customer_id"
    # belongs_to :building, class_name: "Building", foreign_key: "building_id"
    # belongs_to :battery, class_name: "Battery", foreign_key: "baterry_id"
    # belongs_to :column, class_name: "Column", foreign_key: "column_id"
    # belongs_to :elevator, class_name: "Elevator", foreign_key: "elevator_id"
    # belongs_to :employee, class_name: "Employee", foreign_key: "employee_id"
end

app/controllers/interventions_controller.rb
class InterventionsController < ApplicationController
    before_action :set_intervention, only: %i[ show edit update destroy ]

    # def index
    #     @intervention = Intervention.all
    #   end
    
      def show
      end
    
      def new
        @intervention = Intervention.new
      end
    
    #   def edit
    #   end


    # GET /interventions/customer_buildings
    # param customer_id
    def customer_buildings
      @customer_buildings = Customer.find(params[:customer_id]).buildings
      render plain: @customer_buildings.to_json
    end

    # GET /interventions/building_batteries
    # param building_id
    def building_batteries
      @building_batteries = Building.find(params[:building_id]).batteries
      render plain: @building_batteries.to_json
    end

    # GET /interventions/batterie_columns
    # param batterie_id
    def batterie_columns
      @batterie_columns = Battery.find(params[:battery_id]).columns
      render plain:@batterie_columns.to_json
    end

    # GET /interventions/column_elevators
    # param column_id
    def column_elevators
      @column_elevators = Column.find(params[:column_id]).elevators
      render plain: @column_elevators.to_json
    end
    
    # GET /interventions/elevator_select
    # param elevator_id
    # def elevator_select
    #   render plain: params[:elevator_id]
    # end    

    # GET /interventions/company_employees
    # param employee_id    
    def company_employees
      @company_employees = Employees.find_by(title)
      render plain: @company_employees.to_json
    end   


  def create
    
    @intervention = Intervention.new(intervention_params)
    @intervention.author = 1
    @intervention.status = "Pending"
    @intervention.result = "Incomplete"
    @intervention.start_date = DateTime.now
    @intervention.end_date = ""
    
    respond_to do |format|
        if @intervention.save

        intervention_form = {
          email: "rocket_elevator_client@test.com", 
          priority: 1, 
          status: 2,
          type: "Incident",
          subject: "From #{@intervention.customer_id}",
          description: "BuildingID : #{@intervention.building_id}, BatteryID: #{@intervention.battery_id}, ColumnID: #{@intervention.column_id}, ElevatorID: #{@intervention.elevator_id}, TheEmployee: #{@intervention.employee_id}, Description: #{@intervention.report}",
        }.to_json
        intervention_quote = RestClient::Request.execute(
          method: :post, 
          url: "https://rocketelevator-support.freshdesk.com/api/v2/tickets",
          user: ENV['FRESHDESK_KEY'],
          password: "x",
          headers: {
            content_type: "application/json"
          },
          payload: intervention_form
        )


        format.html { redirect_to root_path, notice: "intervention was successfully created." }
        # format.json { render :show, status: :created, location: @intervention }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @intervention.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @intervention.update(intervention_params)
        format.html { redirect_to interventions_url(@intervention), notice: "Intervention was successfully updated." }
        format.json { render :show, status: :ok, location: @intervention }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @intervention.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @intervention.destroy

    respond_to do |format|
      format.html { redirect_to interventions_url, notice: "Intervention was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
  # #   # Use callbacks to share common setup or constraints between actions.
    def set_intervention
      @intervention = Intervention.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def intervention_params
      params.require(:intervention).permit(:author, :customer_id, :building_id, :battery_id, :column_id, :elevator_id, :employee_id, :start_date, :end_date, :result, :report, :status)
    end
end

app/helpers/interventions_helper.rb
module InterventionsHelper
end

app/views/interventions/_form.html.erb
<%= form_with(model: intervention, local: true) do |f| %>

  <% if intervention.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(intervention.errors.count, "error") %> prohibited this intervention from being saved:</h2>

      <ul>
      <% intervention.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<center> 

  <h1>
    <bold> 
        INTERVENTION TICKET
    </bold>
  </h1> 

  <div>
      <%= f.label :customer_id, "Select Customer" %> 
      <%= f.collection_select :customer_id, Customer.order(:name), :id, :name %> 
  </div>

  <br>

  <div>
      <select name="intervention[building_id]" id="intervention_building_id">
      </select>
  </div>

  <br>

  <div>
      <select name="intervention[battery_id]" id="intervention_battery_id">
      </select>
  </div>

  <br>

  <div>
      <select name="intervention[column_id]" id="intervention_column_id">
      </select>
  </div>

  <br>

  <div>
      <select name="intervention[elevator_id]" id="intervention_elevator_id">
      </select>
  </div>

  <div class="allEmployees">
      <%= f.label :employee_id, "Top Employees" %> 
      <%= f.collection_select :employee_id, Employee.order(:id), :id, :title %> 
  </div>

  <div class="longMessage">
      <%= f.label :report, "Description" %>
      <%= f.text_area :report, :cols => 50, :rows => 10, :style => 'resize: none'%>
  </div>

  <div class="actions">
      <%= f.submit %>
  </div>
</center>
<% end %>

app/views/interventions/edit.html.erb
<h1>Editing Intervention</h1>

<%= render 'form', intervention: @intervention %>

<%= link_to 'Show', @intervention %> |
<%= link_to 'Back', interventions_path %>

app/views/interventions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Interventions</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @interventions.each do |intervention| %>
      <tr>
        <td><%= link_to 'Show', intervention %></td>
        <td><%= link_to 'Edit', edit_intervention_path(intervention) %></td>
        <td><%= link_to 'Destroy', intervention, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Intervention', new_intervention_path %>

app/views/interventions/new.html.erb
<h1>New Intervention</h1>

<%= render 'form', intervention: @intervention %>

<%= link_to 'Back', interventions_path %>

app/views/interventions/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_intervention_path(@intervention) %> |
<%= link_to 'Back', interventions_path %>